---
- name: "Assuming AWX role"
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - "./vars/all.yml"
  tasks:
    - name: Echo printenv
      ansible.builtin.shell: printenv
      
    - name: Get Env Password
      ansible.builtin.debug:
        msg: "'{{ lookup('ansible.builtin.env', 'My_Password') }}' is the dev/testdb environment variable."

   
